language: node_js
node_js:
  - "node"
  - "lts/*"
  - "8"
  - "7"
  - "6"
services:
  - mongodb
install:
  - npm install
before_script:
  - sleep 15
script:
  - npm run docs
  - npm test
after_success:
  - npm run coverage
